@startuml
state Expired
state Cancelled
state Deferred
state Requested
state Offered
state Issued
state Ready
state Claiming_in_Progress
[*] --> Offered : Created at start
[*] --> Requested : Created at start
Requested --> Issued : Issue
Requested --> Cancelled : Cancel
Requested --> Expired : Expire
Offered --> Cancelled : Cancel
Offered --> Expired : Expire\n[invalidateOfferData]
Offered --> Claiming_in_Progress : Claim
Claiming_in_Progress --> Expired : Expire\n[invalidateOfferData]
Claiming_in_Progress --> Deferred : Defer
Claiming_in_Progress --> Issued : Issue\n[invalidateOfferData]
Claiming_in_Progress --> Cancelled : Cancel\n[invalidateOfferData]
Deferred --> Ready : Ready
Deferred --> Expired : Expire\n[invalidateOfferData]
Deferred --> Cancelled : Cancel\n[invalidateOfferData]
Ready --> Issued : Issue\n[invalidateOfferData]
Ready --> Expired : Expire\n[invalidateOfferData]
Ready --> Cancelled : Cancel
Ready --> Ready : Ready
Issued --> Issued : Issue
Cancelled --> Cancelled : Cancel
@enduml
