@startuml
state Expired
state Requested
state Cancelled
state Claiming_in_Progress
state Offered
state Ready
state Deferred
state Issued
[*] --> Offered : Created at start
[*] --> Requested : Created at start
Requested --> Issued : Issue
Requested --> Cancelled : Cancel
Offered --> Cancelled : Cancel
Offered --> Expired : Expire\n[invalidateOfferData]
Offered --> Claiming_in_Progress : Claim
Offered --> Requested : Request
Claiming_in_Progress --> Expired : Expire\n[invalidateOfferData]
Claiming_in_Progress --> Deferred : Defer
Claiming_in_Progress --> Issued : Issue\n[invalidateOfferData]
Deferred --> Ready : Ready
Deferred --> Expired : Expire\n[invalidateOfferData]
Ready --> Issued : Issue\n[invalidateOfferData]
Ready --> Expired : Expire\n[invalidateOfferData]
@enduml
