@startuml
state Cancelled
state Deferred
state Ready
state Claiming_in_Progress
state Issued
state Requested
state Expired
state Offered
[*] --> Offered : Created at start\n
note on link
Only for initial
 requests
not renewal
end note

[*] --> Requested : Created at start\n
note on link
Only for renewal
 requests
end note

Requested --> Issued : Issue
Requested --> Cancelled : Cancel
Requested --> Expired : Expire
Offered --> Cancelled : Cancel\n
note on link
Process can be
cancelled as long
as the vc is not ISSUED
end note

Offered --> Expired : Expire\ninvalidateOfferData()
Offered --> Claiming_in_Progress : Claim
Claiming_in_Progress --> Expired : Expire\ninvalidateOfferData()
Claiming_in_Progress --> Deferred : Defer
Claiming_in_Progress --> Issued : Issue\n
note on link
only no deferred
end note

Claiming_in_Progress --> Cancelled : Cancel\ninvalidateOfferData()
Deferred --> Ready : Ready\n[isDeferredOffer]
note on link
Guard to allow
READY transition
only for deferred offers
end note

Deferred --> Expired : Expire\ninvalidateOfferData()
Deferred --> Cancelled : Cancel\ninvalidateOfferData()
Ready --> Issued : Issue\ninvalidateOfferData()
Ready --> Expired : Expire\ninvalidateOfferData()
Ready --> Cancelled : Cancel
Ready --> Ready : Ready
Issued --> Issued : Issue
Cancelled --> Cancelled : Cancel
@enduml
