@startuml
state ISSUED
state SUSPENDED
state REVOKED
[*] --> ISSUED : ISSUE
ISSUED --> SUSPENDED : SUSPEND
ISSUED --> ISSUED : ISSUE
SUSPENDED --> ISSUED : ISSUE
ISSUED --> REVOKED : REVOKE
SUSPENDED --> REVOKED : REVOKE
REVOKED --> REVOKED : REVOKE
SUSPENDED --> SUSPENDED : SUSPEND
@enduml
