@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "*domain*",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "*Dto;*Mapper;*Properties;*Exception",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": false,
    "showMethods": false,
    "showMethodParameterNames": false,
    "showMethodParameterTypes": false,
    "showMethodReturnType": false,
    "showPackageLevels": 5,
    "showDetailedClassStructure": false
  },
  "rootClass": "ch.admin.bj.swiyu.issuer.infrastructure.web.signer.IssuanceController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_92668751 { 
   	label=admin
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_969162937 { 
   	label=bj
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1256842502 { 
   	label=swiyu
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   subgraph cluster_297046061 { 
   	label=issuer
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   subgraph cluster_1073771132 { 
   	label=infrastructure
	labeljust=l
	fillcolor="#b0b0b0"
	style=filled
   
   IssuanceController281199067[
	label="(C)IssuanceController"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2017206988 { 
   	label=common
	labeljust=l
	fillcolor="#b0b0b0"
	style=filled
   
   CacheCustomizer1858348955[
	label="(C)CacheCustomizer"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_857347596 { 
   	label=service
	labeljust=l
	fillcolor="#b0b0b0"
	style=filled
   
   BusinessIssuerRenewalApiClient1938500277[
	label="(C)BusinessIssuerRenewalApiClient"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

CredentialBuilder354864683[
	label="(C)CredentialBuilder"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

CredentialFormatFactory354864683[
	label="(C)CredentialFormatFactory"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

CredentialManagementService354864683[
	label="(C)CredentialManagementService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

CredentialService354864683[
	label="(C)CredentialService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

DemonstratingProofOfPossessionService354864683[
	label="(C)DemonstratingProofOfPossessionService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

DemonstratingProofOfPossessionValidationService354864683[
	label="(C)DemonstratingProofOfPossessionValidationService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

EncryptionService354864683[
	label="(C)EncryptionService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

EventProducerService2070051252[
	label="(C)EventProducerService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

HolderBindingService354864683[
	label="(C)HolderBindingService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

NonceService354864683[
	label="(C)NonceService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

OAuthService354864683[
	label="(C)OAuthService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];
} 
} 
} 
} 
} 

'edges    
CredentialService354864683 -> BusinessIssuerRenewalApiClient1938500277[label="renewalApiClient
[0..1]"];
CredentialService354864683 -> CredentialFormatFactory354864683[label="vcFormatFactory
[0..1]"];
CredentialService354864683 -> CredentialManagementService354864683[label="credentialManagementService
[0..1]"];
CredentialService354864683 -> EncryptionService354864683[label="encryptionService
[0..1]"];
CredentialService354864683 -> EventProducerService2070051252[label="eventProducerService
[0..1]"];
CredentialService354864683 -> HolderBindingService354864683[label="holderBindingService
[0..1]"];
CredentialService354864683 -> OAuthService354864683[label="oAuthService
[0..1]"];
DemonstratingProofOfPossessionService354864683 -> DemonstratingProofOfPossessionValidationService354864683[label="demonstratingProofOfPossessionValidationService
[0..1]"];
DemonstratingProofOfPossessionService354864683 -> NonceService354864683[label="nonceService
[0..1]"];
DemonstratingProofOfPossessionService354864683 -> OAuthService354864683[label="oAuthService
[0..1]"];
EncryptionService354864683 -> CacheCustomizer1858348955[label="cacheCustomizer
[0..1]"];
IssuanceController281199067 -> CredentialService354864683[label="credentialService
[0..1]"];
IssuanceController281199067 -> DemonstratingProofOfPossessionService354864683[label="demonstratingProofOfPossessionService
[0..1]"];
IssuanceController281199067 -> EncryptionService354864683[label="encryptionService
[0..1]"];
IssuanceController281199067 -> NonceService354864683[label="nonceService
[0..1]"];
IssuanceController281199067 -> OAuthService354864683[label="oauthService
[0..1]"];
    
}
@enduml